name: CI/CD using github actions & docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # 백엔드 Gradle 빌드
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Inject .env for Backend
      run: |
        echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" > ./backend/demo/.env
        echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> ./backend/demo/.env
        echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> ./backend/demo/.env


    - name: Build Backend with Gradle Skip tests
      run: ./gradlew build -x test
      working-directory: ./backend/demo

    # Docker 로그인 (공통)
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # 백엔드 Docker build & push
    - name: Docker build & push - Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app ./backend/demo
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-app

    # 프론트엔드 환경변수 파일 생성
    - name: Inject .env.production for Frontend
      run: |
        echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" > ./frontend/app/.env.production


    # 프론트엔드 Docker build & push
    - name: Docker build & push - Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app ./frontend/app
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app

    # EC2 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Docker Hub에서 최신 이미지 pull
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

          # 기존 컨테이너 정리
          sudo docker stop frontend || true
          sudo docker rm frontend || true
          sudo docker stop backend || true
          sudo docker rm backend || true

          # backend.env 파일 생성 (DB 정보 주입)
          echo SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} > /home/ubuntu/backend.env
          echo SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} >> /home/ubuntu/backend.env
          echo SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} >> /home/ubuntu/backend.env


          # 컨테이너 실행
          sudo docker run -d --name backend --env-file /home/ubuntu/backend.env -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
          sudo docker run -d --name frontend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

          # 정리
          sudo docker container prune -f
          sudo docker image prune -a -f
